version: "2"
services:        
  database:
    container_name: dictionary_postgres
    image: postgres
    ports:
        - "5432:5432"
    environment: 
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=jlpt

    volumes:
        - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql